### ISSUE TITLE
Declaration of `VideoTagWithPosterRenderer::render` must be compatible 

### ISSUE THREAD

**Issue by liayn** [b13/poster-image#1]
> PHP Fatal error:  Declaration of B13\PosterImage\VideoTagWithPosterRenderer::render(TYPO3\CMS\Core\Resource\FileInterface $file, $width, $height, array $options = []) must be compatible with TYPO3\CMS\Core\Resource\Rendering\VideoTagRenderer::render(TYPO3\CMS\Core\Resource\FileInterface $file, $width, $height, array $options = [], $usedPathsRelativeToCurrentScript = false) in .../poster_image/Classes/VideoTagWithPosterRenderer.php on line 44

Core v11

**Comment by mtness** [comment]
Hi there, this is still an issue for me here - 
tried to install this in a current V11, but got the exact same erroer even though i installed the latest version.

**Comment by liayn** [comment]
The problem with the current solution is that DI tries to load both versions of VideoTagWithPosterRenderer, which of course fails with the same error.

The possible solution is to move the version distinction into the `VideoTagWithPosterRenderer.php` file and declare one or the other class version depending on the core version.

**Comment by mtness** [comment]
Thank you @liayn !
@bmack  Hi there, we still need a new git tag to update packagist integration.
Additionally, the require php section doesn't seem right, don't we need 8.2 + 8.3 there, too ?

**Comment by liayn** [comment]
@mtness  I can create PRs. git tag is not required strictly (`dev-master` can be required), but helpful.
